[build]
  base = "frontend"
  command = "npm ci --prefer-offline --no-audit && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--production=false"
  CI = "true"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"